### ISSUE TITLE
renomar textim-editor para textim?

### ISSUE THREAD

**Issue by nichdemos** [zekicarvalho/textim-editor#15]
Oi @zekicarvalho.

Uma ideia que tive hoje seria deixar o repositório como textim, em vez de textim-editor. Sou programador frontend(html, js, css, php, frameworks-js, vuejs, react etc). Algo que me importo nome é com a parte visual, design e também a forma como cada coisa está organizada(design patterns, arquitetura)...

Queria saber se você acha se isso faz sentido, faz sentido deixar o repo como textim em vez de textim-editor? acha que ao mudar o nome ficaria melhor?

**Comment by zekicarvalho** [comment]
@nichdemos Acho que faz sentido. 
Vou alterar.
