### ISSUE TITLE
patrocínio no Textim?

### ISSUE THREAD

**Issue by ghost** [zekicarvalho/textim-editor#21]
Oi @zekicarvalho, como tú tá?

Uma dúvida de quem está contribuindo aos poucos aqui, já pensou em transformar a solução opensource em algo comercial?

***Prós***
- quando uma aplicação opensource torna-se comercial, ela pode ajudar uma comunidade de desenvolvedores junto ao desenvolvedor principal
- todo mundo quer ganhar dinheiro para viver de uma forma boa, confortável e com certa saúde e bem estar. O dinheiro pode possibilitar isso, mas não somente isso.
- existe o recurso no GitHub que torna isso possível
- podemos viabilizar soluções ambientais com o dinheiro da comunidade para isso, e ao mesmo tempo conseguir viver de uma forma saudável e sustentável (e da maneira como podemos sonhar ou alcançar)

***Contras***
- nem todo mundo é movido por conforto, bem estar ou vida boa; nem mesmo com bem material ou dinheiro
- talvez isso não faça sentido, pois é uma aplicação mínima
- talvez outros desenvolvedores queiram contribuir sem recursos financeiros
- dependência de fornecedor: isso significa que talvez sejamos fornecedores no futuro deste software, de tal forma que muita gente dependa da gente. E algumas pessoas, sentem-se aprisionadas pelos fornecedores de software

***o que pensa dos prós e contras aqui? faz sentido? quero sua opinião!***

**Comment by zekicarvalho** [comment]
Não é meu objetivo.
