### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by codehangen** [zekicarvalho/textim-editor#9]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by zekicarvalho** [comment]
@codehangen Infelizmente tem um tempo que não atualizo ele, mas pode ficar a vontade para sugerir e modificar.

**Comment by codehangen** [comment]
Oi zekicarvalho.

> @codehangen Infelizmente tem um tempo que não atualizo ele, mas pode ficar a vontade para sugerir e modificar.


valeu pela mensagem, farei o fork hj para ajudar.
